### PR TITLE
Missing client token

### LINKED ISSUE #2: Missing client token
When using the read functionality I am getting back an error of 'missing client token' even after I have supplied it. Using straight bash with the token and vault url provides the expected data. I believe that the token is supposed to be passed with the header `X-Vault-Token: SOME_TOKEN`

Code I'm running:

``` javascript
  var vault = new Vault({
    endpoint: process.env.VAULT_URL,
    token: process.env.VAULT_TOKEN
  })

  vault.read('secret/test/message', function (err, val) {
    if (err) {
      throw err
    }

    console.log(val)
  })
```

Error I see:

``` bash
~/Code/vault-node
»  DEBUG=vault node index.js
  vault read secret/test/message +0ms
  vault GET https://MY_VAULT_CLUSER:8200/v1/secret/test/message +3ms
  vault requestOptions: {"jar":{"_jar":{"version":"tough-cookie@2.2.1","storeType":"MemoryCookieStore","rejectPublicSuffixes":true,"cookies":[{"key":"token","value":"SOME_TOKEN","domain":"MY_VAULT_CLUSTER","path":"/","hostOnly":true,"pathIsDefault":true,"creation":"2016-02-01T18:35:13.281Z","lastAccessed":"2016-02-01T18:35:13.281Z"}]}},"method":"GET","json":null,"uri":"MY_VAULT_CLUSTER:8200/v1/secret/test/message","followRedirects":true,"followAllRedirects":true} +2ms
  vault headers: {"content-type":"application/json","date":"Mon, 01 Feb 2016 18:35:13 GMT","content-length":"36","connection":"close"} +433ms
  vault RES 400 +0ms
  vault { errors: [ 'missing client token' ] } +0ms
/Users/avi/Code/vault-node/index.js:22
        throw err
              ^
Error: missing client token
    at /Users/avi/Code/vault-node/node_modules/node-vault-js/vault.js:156:13
    at Request._callback (/Users/avi/Code/vault-node/node_modules/node-vault-js/vault.js:208:12)
    at Request.self.callback (/Users/avi/Code/vault-node/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/avi/Code/vault-node/node_modules/request/request.js:1036:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/avi/Code/vault-node/node_modules/request/request.js:963:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
~/Code/vault-node
»
```

### PR DESCRIPTION
**Pull request by wasbazi**
- Updates how the client token is passed to vault, fixes #2 
- Updates the documentation for usability

### CODE REVIEW

**Comment by ekristen** [comment]
Thanks for the PR. I'll review it. The cookie method was originally taken from the original project and definitely works, I'm using this library as is.

However the vault docs do suggest using the header, so I'll run some test (write some too) and take a look at merging.

**Comment by wasbazi** [comment]
I was having some issues with the cookie method so I figured I'd update it to the docs, though that is good to hear that the cookie method is working for you. If you need a hand with any tests for the repo let me know.

**Comment by ekristen** [comment]
I'm all for merging your PR, but without tests I just need to jump in and do some testing to make sure I don't break anything, or I can just merge and release a new major version to prevent any backwards compatibility issues. 

If you are interested in writing test, etc, I'm all for it and would be more than willing to consider adding you on as a collaborator, etc should you be interested.

**Comment by wasbazi** [comment]
Absolutely! Wouldn't want to merge it in without confidence that it works. I can look into the level of effort for writing tests and if I'm up for it I would happily be a collaborator.

It makes sense to me to bump the version for this change so that we don't have to worry about backwards compatibility.

**Pull request merged**
